version: '3'
services:
  webapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword